renaming from vue-ts to bsc-thesis

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,12 +4,10 @@ default:
   # Validate that the repository contains a package.json and extract a few values from it.
   before_script:
     - ls
-    - cd vue-ts
-    - |
       if [[ ! -f package.json ]]; then
-        echo "No package.json found! A package.json file is required to publish a package to GitLab's NPM registry."
-        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#creating-a-project'
-        exit 1
+      echo "No package.json found! A package.json file is required to publish a package to GitLab's NPM registry."
+      echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#creating-a-project'
+      exit 1
       fi
     - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
     - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
@@ -52,7 +50,6 @@ e2e-tests:
   variables:
     SELENIUM_HOST: selenium__standalone-chrome
   script:
-    - cd vue-ts
     - yarn install --cache-folder .yarn
     - yarn test:e2e
   artifacts:
